[package]
name = "hashpass"
version = "0.1.0"
edition = "2024"
authors = ["Tahcin Ul Karim (Mycin)"]
description = "A CLI tool for password hashing and verification"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
bcrypt = "0.15"
thiserror = "1.0"
